### ISSUE TITLE
Sprint todo

### ISSUE THREAD

**Issue by lrettig** [ewasm/ewasm-explorer#6]
- [ ] Deploying ewasm contracts (paste in wast code and deploy it as a contract)
- [ ] When you deploy a contract, calculate new address and add to accounts list (depends on previous)
- [ ] Optimization: don't fetch any account data when it's not expanded
- [ ] When an account is expanded, and a storage key changes, highlight this in color
- [ ] Tab or toggle to switch between WAST and wasm bytecode or EVM bytecode / opcodes list
- [ ] Refactor, clean up codebase

**Comment by axic** [comment]
@cdetrio is this repo deprecated?

**Comment by cdetrio** [comment]
It has some react UI features that would be nice to port over to etherchain-light. But yes it is deprecated

**Comment by axic** [comment]
Can you create an issue in the testnet repo or the eterchain-light repo explaining what needs to be ported over? I'll just mark this repo then "orphaned", so there's some visibility what is useful to work on and what isn't.
